### ISSUE TITLE
Issue not finding "self._init_params" attribute with run.py

### ISSUE THREAD

**Issue by enzoampil** [quadflor/Quadflor#5]
Error while executing configuration of line 7:
Traceback (most recent call last):
  File "run.py", line 983, in <module>
    run(args)
  File "run.py", line 539, in run
    results = _run_experiment(X, Y, kf, validation_set_indices, mlb, X_raw, Y_raw, tr, options)
  File "run.py", line 294, in _run_experiment
    clf = create_classifier(options, Y_train.shape[1])  # --- INTERACTIVE MODE ---
  File "run.py", line 589, in create_classifier
    "mcknn": MeanCutKNeighborsClassifier(n_neighbors=options.k, algorithm='brute', metric='cosine', soft=False),
  File "/home/jupyter/Quadflor/Code/lucid_ml/classifying/meancut_kneighbor_classifier.py", line 17, in __init__
    self._init_params(n_neighbors=n_neighbors,
AttributeError: 'MeanCutKNeighborsClassifier' object has no attribute '_init_params'

**Comment by lgalke** [comment]
The MeanCutKNeighborsClassifier can be considered as deprecated. Some update in sklearn has apparrently changed the structure of its base class (NeighborsBase). It is not worth keeping keeping it up-to-date because it is very similar to BR-kNN-b. MeanCutKNeighbors uses global average to determine how many labels should be assigned, whereas BR-kNN-b uses the average label count within the nearest neighbors. I'd recommend to use BR-kNN-b instead.

For this reason, the `"mcknn":...` line in the dict was commented out since January. It's now time to remove the code for mcknn altogether.
